# Generated by Django 3.0.8 on 2020-08-06 17:25

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('descricao_venda', models.TextField(verbose_name='Descrição da Venda')),
                ('data_compra', models.DateField(default=datetime.datetime.now, verbose_name='Data da Compra')),
                ('data_vencimento', models.DateField(default=datetime.datetime.now, verbose_name='Data Vencimento')),
                ('qtParcelas', models.IntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('status', models.CharField(choices=[('andamento', 'Andamento'), ('pago', 'Pago')], default='Andamento', max_length=10)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descricao')),
                ('valorParcela', models.FloatField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcela_vendas', to='venda.Venda')),
            ],
        ),
    ]
