# Generated by Django 3.0.8 on 2020-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('telefone', models.CharField(max_length=32)),
                ('CPF', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], max_length=7, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
    ]
